### PR TITLE
Updated Mesos probe documentation

### PR DESCRIPTION
**Pull request by jose-sanchezm**

### CODE REVIEW

**Comment by orviz** [comment]
retest this please

**Comment by orviz** [comment]
retest this please

**Comment by orviz** [comment]
retest this please

**Comment by jose-sanchezm** [comment]
Still the same problem

**Comment by orviz** [comment]
The error seems to be related to the instance where the test is executed, which in our case is a Debian-based Docker container. A little research on this points to [surefire-plugin version](https://stackoverflow.com/questions/46670582/docker-maven-failsafe-surefire-starting-fork-fails-with-the-forked-vm-termin). 

Based on my little knowledge of Java, could you please give it a try? Even better, you can reproduce the execution environment by running the `mvn test` using same Docker image [indigodatacloud/ci-images:java](https://cloud.docker.com/u/indigodatacloud/repository/registry-1.docker.io/indigodatacloud/ci-images/tags)

**Comment by caifti** [comment]
the first issue mentiond " Your image failed to build in Docker Hub " is because the automated build in Dockerhub was wrongly defined - it didn't point to the correct path to the Dockerfile. I've corrected it (in DockerHub) and restarted the build. Now is "in progress".

**Comment by caifti** [comment]
the build in DockerHub failed - and the error can be found at: https://cloud.docker.com/u/indigodatacloud/repository/registry-1.docker.io/indigodatacloud/monitoring/builds/f8718339-1170-441a-b7d3-af6a490fe342
Step 14/16 : COPY /$WAR_NAME.war $JBOSS_HOME/standalone/deployments/$WAR_NAME.war.zip
COPY failed: stat /var/lib/docker/tmp/docker-builder960606091/MonitoringWrapper.war: no such file or directory

**Pull request merged**
